# Generated by Django 5.2.4 on 2025-08-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='uploadedlog',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(db_index=True, default='viewer', max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadedlog',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='analyzer_cu_email_775057_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='analyzer_cu_role_87c2c5_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active', 'email'], name='analyzer_cu_is_acti_ad466e_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedlog',
            index=models.Index(fields=['user', 'uploaded_at'], name='analyzer_up_user_id_6e53d4_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedlog',
            index=models.Index(fields=['-uploaded_at'], name='analyzer_up_uploade_b74e3c_idx'),
        ),
    ]
